# Generated by Django 2.2 on 2020-08-01 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_remove_article_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='text',
            field=models.TextField(default=False, max_length=3000, verbose_name='Текст'),
            preserve_default=False,
        ),
    ]
