# Generated by Django 2.2 on 2020-08-11 05:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_article_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Время публикации'),
        ),
    ]
