# Generated by Django 2.2 on 2020-08-19 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20200817_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='tags',
            new_name='tags_old',
        ),
    ]
