# Generated by Django 2.2 on 2020-08-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20200819_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='webapp.Tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags_old',
            field=models.ManyToManyField(blank=True, related_name='articles_old', through='webapp.ArticleTag', to='webapp.Tag', verbose_name='Теги'),
        ),
    ]
